# Generated by Django 5.2.11 on 2026-03-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buynow',
            name='order_number',
            field=models.CharField(blank=True, default='LqY7JtgSy5', max_length=20),
        ),
    ]
