# Generated by Django 5.2.11 on 2026-03-03 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0002_alter_buynow_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buynow',
            name='order_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='buynow',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danceapp.costumevariant'),
        ),
    ]
