# Generated by Django 5.2.11 on 2026-03-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0003_alter_buynow_order_number_alter_buynow_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumevariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='costume_variants/'),
        ),
    ]
