# Generated by Django 5.2.11 on 2026-03-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('danceapp', '0004_costumevariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumevariant',
            name='image',
        ),
    ]
